### ISSUE TITLE
Fix covers extending outside the boundary in Chrome

### ISSUE THREAD

**Issue by connorshea** [connorshea/VideoGameList#1193]
For example: https://vglist.co/games/29115 or https://vglist.co/games/28616

<img width="701" alt="Screen Shot 2020-05-02 at 12 48 49 PM" src="https://user-images.githubusercontent.com/2977353/80873138-b4c29480-8c73-11ea-9662-6fe50c83099f.png">

This only happens in Chrome, of course. 🙄  It also extends outside its normal space on smaller viewport widths.

**Comment by PanisSupraOmnia** [comment]
Example on small screen:
![image](https://user-images.githubusercontent.com/2047515/80873361-2f3fe400-8c75-11ea-8c78-52d51b6fc4e3.png)
