### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by connorshea** [connorshea/VideoGameList#18]
Need to figure out a few things:

- Probably Heroku
- Hobby dynos are probably fine for now
- We'll definitely need the 10M rows in Postgres
- We'll need a mail provider
- We'll need a way to store ActiveStorage attachments

**Comment by AnthonySuper** [comment]
Use Heroku with the first tier of non-hobby dyno (for $25/month you really can't go wrong). You'll need a pretty big Heroku postgres for ten million rows, sadly.

For mail I use amazon SES. It's pretty easy to setup, and it's what ArtWorkDraft uses. For ActiveStorage I use S3 because it's very easy and very cheap.

**Comment by connorshea** [comment]
Yeah but it’s only $9/mo for 10M rows so ¯\_(ツ)_/¯ 

And the only tier below that is free for 10k

**Comment by connorshea** [comment]
Maybe worth considering DigitalOcean: https://www.digitalocean.com/pricing/

**Comment by connorshea** [comment]
I made some progress on this with #138

**Comment by connorshea** [comment]
NOTE TO SELF: fix whatever this is https://github.com/connorshea/ContinueFromCheckpoint/blob/4b1a356208691973bdd2ead549376b9f75c40a54/Dockerfile#L14

**Comment by connorshea** [comment]
Update: I gave up on using Docker, started using DigitalOcean, deployed the site to DigitalOcean, and I've currently got the site itself mostly set up, the image hosting set up, the database set up, and now I just need to configure the SSL certificate and email.

**Comment by connorshea** [comment]
This issue might be effecting my ability to disallow unsafe-eval in my CSP config, unfortunately: https://github.com/rails/webpacker/issues/1520#issuecomment-399112369

Will need to investigate that later, for now I'm just going to loosen the CSP config.

**Comment by connorshea** [comment]
Everything is set up, although emails won't actually send until Amazon has approved my request to leave the sandbox. So I'll leave this issue open for a bit longer.

**Comment by PanisSupraOmnia** [comment]
Feel free to ignore, but I would recommend [Capistrano](https://capistranorb.com/) for actual deployment. The deployment rake task that exists right now is a good start that should translate to Capistrano pretty painlessly.

**Comment by connorshea** [comment]
Emails work now \o/ Closing.
