### ISSUE TITLE
while setup

### ISSUE THREAD

**Issue by rubyblackforce** [connorshea/VideoGameList#492]
while setting up project i am getting an error at enabling extension "pg_trgm" .Insufficient priviliges even though i am superuser.

**Comment by connorshea** [comment]
Could you provide more info? What OS are you on, what Ruby version are you on, and what Postgres version are you running?

**Comment by rubyblackforce** [comment]
Hi sry for for late reply.I am using ubuntu-18.04,ruby-2.6.3,postgres-11.x

**Comment by rubyblackforce** [comment]
after disabling the enable extension 'pg_trgm'. rails db:setup worked but i think its very much needed

**Comment by connorshea** [comment]
The Postgres user it runs the migrations as should have the same name as the operating system user that initialized the database.

So you need to give `likith` Super User permissions with `ALTER ROLE likith SUPERUSER` :)
