### ISSUE TITLE
Build on heroku fails 

### ISSUE THREAD

**Issue by s3lm** [connorshea/VideoGameList#522]
from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/instrument.rb:35:in `trace'

	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/bin/support/ruby_compile:15:in `<main>'

 !     Push rejected, failed to compile Ruby app.

 !     Push failed

**Comment by connorshea** [comment]
Could you give more info on what you’re trying to do, and some more logs? I don’t have much to go on with this.
