### ISSUE TITLE
Make average rating a column that's tracked statically

### ISSUE THREAD

**Issue by connorshea** [connorshea/VideoGameList#777]
And then either update it on a daily basis (cron job? ActiveJob?) or have it update every time someone changes a related game purchase.

**Comment by AnthonySuper** [comment]
Database triggers are another option, albeit one that is a bit more complicated (but probably faster in the long run)

**Comment by connorshea** [comment]
Is there a way to create triggers via Rails or do I have to use a migration?

**Comment by AnthonySuper** [comment]
Gotta use a migration, sadly. I think there might be a few libraries but it's not native.
